# info: https://voltwu.github.io/blog/docker/2021/01/21/using-nexus3-as-your-repository-a-simple-guide/
# get initial admin account password: docker container exec nexus3_nexus3_1 cat nexus-data/admin.password
version: "3.3"
services:
  nexus3:
    restart: always
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - /media/Data/Nexus3/nexus-data/:/nexus-data
