# info: https://voltwu.github.io/blog/docker/2021/01/21/using-nexus3-as-your-repository-a-simple-guide/
# get initial admin account password: docker container exec nexus3-nexus3-1 cat /nexus-data/admin.password
version: "3.3"
services:
  nexus3:
    image: sonatype/nexus3
    ports:
      - "38081:8081"
    volumes:
      - nexus-data:/nexus-data
volumes:
    nexus-data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './nexus-data'
