version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - zookeeper-data:/data
      - zookeeper-logs:/datalog

  kafka-1:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-1:9093
      0: SSL:SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka-1.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: password
      KAFKA_SSL_KEY_PASSWORD: password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka-1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    volumes:
      - kafka-1-data:/kafka/data
      - ./ssl:/var/private/ssl

  kafka-2:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "9095:9095"
      - "9096:9096"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-2:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka-2.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: password
      KAFKA_SSL_KEY_PASSWORD: password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka-2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    volumes:
      - kafka-2-data:/kafka/data
      - ./ssl:/var/private/ssl

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-1-data:
  kafka-2-data:

