version: '3.7'
services:
    opensearch:
        image: opensearchproject/opensearch:1.3.11
        environment:
            discovery.type: single-node
            plugins.security.disabled: true # disable https and logins
            compatibility.override_main_response_version: true
        ports:
            - 9200:9200
            - 9600:9600 # required for Performace Analizer
            
    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:1.3.11
        ports:
            - 5601:5601
        environment:
            OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
            DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"